dist: trusty
sudo: false

jobs:
  include:
    - stage: Build and push docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/alpinewithtools .
      - docker push $DOCKER_USERNAME/alpinewithtools